import json
import logging
from openai import AsyncOpenAI
from pydantic import ValidationError

from app.core.config import settings
from app.engine.schema import LLMActionResponse

logger = logging.getLogger(__name__)


class LLMGenerationError(Exception):
    """Raised when LLM completion fails due to network error, timeout, or malformed schema."""

    pass


SYSTEM_JSON_INSTRUCTION = (
    "You must respond with valid JSON matching the following schema:\n"
    "{\n"
    '  "actions": [\n'
    '    {"type": "speak", "content": "first short message"},\n'
    '    {"type": "speak", "content": "second follow-up text"},\n'
    '    {"type": "set_timer", "delay_seconds": 30}\n'
    "  ]\n"
    "}\n"
    "Guidelines:\n"
    "- You can include multiple sequential 'speak' actions to send multiple short, natural human-like text messages.\n"
    "- 'delay_seconds' for set_timer must be an integer between 10 and 60.\n"
    "- Return plain text in speak content without HTML/XML tags.\n"
    "- Conversation Continuity: Check the chat history carefully. Never repeat, summarize, or re-generate statements you already sent to the user. Advance the conversation forward."
)



class LLMClient:
    def __init__(
        self,
        api_key: str | None = None,
        base_url: str | None = None,
        model: str | None = None,
        timeout: float = 15.0,
    ):
        self.api_key = api_key if api_key is not None else (settings.OPENAI_API_KEY or "no-key")
        self.base_url = base_url if base_url is not None else (settings.OPENAI_BASE_URL or None)
        self.model = model or settings.OPENAI_MODEL
        self.timeout = timeout

        kwargs: dict[str, str] = {"api_key": self.api_key}
        if self.base_url:
            kwargs["base_url"] = self.base_url

        self.client = AsyncOpenAI(**kwargs)

    async def generate_actions(
        self, messages: list[dict[str, str]]
    ) -> LLMActionResponse:
        payload_messages = [
            {"role": "system", "content": SYSTEM_JSON_INSTRUCTION}
        ] + messages

        endpoint_info = f"base_url={self.base_url}" if self.base_url else "default OpenAI endpoint"
        logger.info(f"[LLM] Requesting completion from model '{self.model}' ({endpoint_info}) with {len(payload_messages)} messages (timeout={self.timeout}s)")

        # Detailed debug log of exact payload sent to LLM
        formatted_payload = json.dumps(payload_messages, indent=2, ensure_ascii=False)
        logger.debug(f"[LLM:PAYLOAD] === SENT TO LLM ===\n{formatted_payload}\n========================")

        try:
            response = await self.client.chat.completions.create(
                model=self.model,
                messages=payload_messages,  # type: ignore
                response_format={"type": "json_object"},
                temperature=0.7,
                timeout=self.timeout,
            )

            raw_content = response.choices[0].message.content or "{}"
            # Detailed debug log of exact response received from LLM
            logger.debug(f"[LLM:RESPONSE] === RECEIVED FROM LLM ===\n{raw_content}\n===========================")

            parsed_json = json.loads(raw_content)
            action_response = LLMActionResponse.model_validate(parsed_json)
            speak_count = sum(1 for a in action_response.actions if a.type == "speak")
            timer_action = next((a for a in action_response.actions if a.type == "set_timer"), None)
            timer_str = f"{timer_action.delay_seconds}s" if timer_action else "None"
            logger.info(f"[LLM] Parsed {len(action_response.actions)} action(s) from LLM (speak_msg_count={speak_count}, requested_timer={timer_str})")
            return action_response

        except ValidationError as e:
            logger.error(f"[LLM] Schema validation failed for response: {e}")
            logger.error(f"[LLM] Raw content that failed validation: {raw_content if 'raw_content' in locals() else 'N/A'}")
            raise LLMGenerationError(f"Schema validation failed: {e}") from e
        except json.JSONDecodeError as e:
            logger.error(f"[LLM] Malformed JSON generated by model: {e}")
            logger.error(f"[LLM] Raw content that failed JSON decode: {raw_content if 'raw_content' in locals() else 'N/A'}")
            raise LLMGenerationError(f"Malformed JSON generated by model: {e}") from e
        except Exception as e:
            logger.error(f"[LLM] API communication failure: {type(e).__name__}: {e}")
            raise LLMGenerationError(f"API communication failure: {e}") from e

