import json
import logging
from openai import AsyncOpenAI
from pydantic import ValidationError

from app.core.config import settings
from app.engine.schema import LLMActionResponse

logger = logging.getLogger(__name__)

SYSTEM_JSON_INSTRUCTION = (
    "You must respond with valid JSON matching the following schema:\n"
    "{\n"
    '  "actions": [\n'
    '    {"type": "speak", "content": "first short message"},\n'
    '    {"type": "speak", "content": "second follow-up text"},\n'
    '    {"type": "set_timer", "delay_seconds": 30}\n'
    "  ]\n"
    "}\n"
    "Guidelines:\n"
    "- You can include multiple sequential 'speak' actions to send multiple short, natural human-like text messages.\n"
    "- 'delay_seconds' for set_timer must be an integer between 10 and 60.\n"
    "- Return plain text in speak content without HTML/XML tags."
)


class LLMClient:
    def __init__(
        self,
        api_key: str | None = None,
        base_url: str | None = None,
        model: str | None = None,
    ):
        self.api_key = api_key if api_key is not None else (settings.OPENAI_API_KEY or "no-key")
        self.base_url = base_url if base_url is not None else (settings.OPENAI_BASE_URL or None)
        self.model = model or settings.OPENAI_MODEL

        kwargs: dict[str, str] = {"api_key": self.api_key}
        if self.base_url:
            kwargs["base_url"] = self.base_url

        self.client = AsyncOpenAI(**kwargs)

    async def generate_actions(
        self, messages: list[dict[str, str]]
    ) -> LLMActionResponse:
        payload_messages = [
            {"role": "system", "content": SYSTEM_JSON_INSTRUCTION}
        ] + messages

        endpoint_info = f"base_url={self.base_url}" if self.base_url else "default OpenAI endpoint"
        logger.info(f"[LLM] Requesting completion from model '{self.model}' ({endpoint_info}) with {len(payload_messages)} messages")

        try:
            response = await self.client.chat.completions.create(
                model=self.model,
                messages=payload_messages,  # type: ignore
                response_format={"type": "json_object"},
                temperature=0.7,
            )

            raw_content = response.choices[0].message.content or "{}"
            logger.debug(f"[LLM] Raw response content: {raw_content}")

            parsed_json = json.loads(raw_content)
            action_response = LLMActionResponse.model_validate(parsed_json)
            logger.info(f"[LLM] Successfully parsed {len(action_response.actions)} action(s) from LLM response")
            return action_response

        except ValidationError as e:
            logger.error(f"[LLM] Schema validation failed for response: {e}")
            return LLMActionResponse(actions=[])
        except json.JSONDecodeError as e:
            logger.error(f"[LLM] Malformed JSON generated by model: {e}")
            return LLMActionResponse(actions=[])
        except Exception as e:
            logger.error(f"[LLM] API communication failure: {type(e).__name__}: {e}")
            return LLMActionResponse(actions=[])
