import json
import logging
from openai import AsyncOpenAI
from pydantic import BaseModel, ValidationError

from app.core.config import settings

logger = logging.getLogger(__name__)


class LLMGenerationError(Exception):
    """Raised when LLM completion fails due to network error, timeout, or malformed schema."""

    pass


class LLMResponse(BaseModel):
    messages: list[str]


SYSTEM_JSON_INSTRUCTION = (
    "SPEAKER IDENTIFICATION & DIALOGUE RULES:\n"
    "- Messages with role 'user' are spoken by the HUMAN USER.\n"
    "- Messages with role 'assistant' are spoken by YOU (the assistant).\n"
    "- Messages with role 'system' are environment or timer notifications.\n"
    "- CRITICAL RULE: NEVER reply to or answer your own previous 'assistant' messages. Only respond to the latest 'user' input or system context.\n\n"
    "You must respond with valid JSON matching the following schema:\n"
    "{\n"
    '  "messages": [\n'
    '    "first short message",\n'
    '    "second follow-up text"\n'
    '  ]\n'
    "}\n\n"
    "Guidelines:\n"
    "- Return a list of natural, conversational strings under the 'messages' key.\n"
    "- Do not prefix your response with roles or headers (e.g., do NOT write 'assistant: hello'). Strictly output only the message content strings.\n"
    "- Do not output HTML, XML, or markdown tags in message content.\n"
    "- Conversation Continuity: Check the chat history carefully. Never repeat, summarize, or re-generate statements you already sent to the user. Advance the conversation forward.\n\n"
    "EXAMPLES:\n"
    "Example 1 (Replying to user message):\n"
    "{\n"
    '  "messages": [\n'
    '    "Hi there! How can I help you today?"\n'
    '  ]\n'
    "}\n\n"
    "Example 2 (Timer expired - sending a follow-up or check-in):\n"
    "{\n"
    '  "messages": [\n'
    '    "Just wanted to check in. Let me know if you need anything else!"\n'
    '  ]\n'
    "}"
)


class LLMClient:
    def __init__(
        self,
        api_key: str | None = None,
        base_url: str | None = None,
        model: str | None = None,
        timeout: float = 15.0,
    ):
        self.api_key = api_key if api_key is not None else (settings.OPENAI_API_KEY or "no-key")
        self.base_url = base_url if base_url is not None else (settings.OPENAI_BASE_URL or None)
        self.model = model or settings.OPENAI_MODEL
        self.timeout = timeout

        kwargs: dict[str, str] = {"api_key": self.api_key}
        if self.base_url:
            kwargs["base_url"] = self.base_url

        self.client = AsyncOpenAI(**kwargs)

    async def generate_actions(
        self, messages: list[dict[str, str]]
    ) -> list[str]:
        payload_messages = messages

        endpoint_info = f"base_url={self.base_url}" if self.base_url else "default OpenAI endpoint"
        logger.info(f"[LLM] Requesting completion from model '{self.model}' ({endpoint_info}) with {len(payload_messages)} messages (timeout={self.timeout}s)")

        try:
            response = await self.client.chat.completions.create(
                model=self.model,
                messages=payload_messages,  # type: ignore
                response_format={"type": "json_object"},
                temperature=0.7,
                timeout=self.timeout,
            )

            raw_content = response.choices[0].message.content or "{}"
            # Detailed debug log of exact response received from LLM
            logger.debug(f"[LLM:RESPONSE] === RECEIVED FROM LLM ===\n{raw_content}\n===========================")

            parsed_json = json.loads(raw_content)
            validated = LLMResponse.model_validate(parsed_json)
            logger.info(f"[LLM] Parsed {len(validated.messages)} sequential message(s) from JSON.")
            return validated.messages

        except ValidationError as e:
            logger.error(f"[LLM] Schema validation failed for response: {e}")
            logger.error(f"[LLM] Raw content that failed validation: {raw_content if 'raw_content' in locals() else 'N/A'}")
            raise LLMGenerationError(f"Schema validation failed: {e}") from e
        except json.JSONDecodeError as e:
            logger.error(f"[LLM] Malformed JSON generated by model: {e}")
            logger.error(f"[LLM] Raw content that failed JSON decode: {raw_content if 'raw_content' in locals() else 'N/A'}")
            raise LLMGenerationError(f"Malformed JSON generated by model: {e}") from e
        except Exception as e:
            logger.error(f"[LLM] API communication failure: {type(e).__name__}: {e}")
            raise LLMGenerationError(f"API communication failure: {e}") from e
